#!/bin/bash

IFS=","

[[ -z $DOTFILES ]] && echo '$DOTFILES variable uninitialized' && exit
[[ -z $STOW_FOLDERS ]] && echo '$STOW_FOLDERS varaible uninitialized' && exit

pushd $DOTFILES >/dev/null

for dir in $STOW_FOLDERS; do
    echo "Installing ${dir}"
    stow -D ${dir}
    stow ${dir}
done
