#!/bin/bash

EWW_BIN="$HOME/.local/bin/eww"

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        ${EWW_BIN} -c $HOME/.config/eww/bar close system music_win audio_ctl \
            prompt_win_off prompt_win_reboot
        rm $HOME/.cache/eww-*.lock
        touch "$LOCK_FILE"
        run && echo "ok good!"
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close calendar
        rm "$LOCK_FILE" && echo "closed"
    fi
}


system() {
    LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open system 
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_MEM" ]]; then
        ${EWW_BIN} -c $HOME/.config/eww/bar close calendar music_win audio_ctl \
            prompt_win_reboot prompt_win_off
        rm $HOME/.cache/eww-*.lock
        touch "$LOCK_FILE_MEM"
        run && echo "ok good!"
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close system 
        rm "$LOCK_FILE_MEM" && echo "closed"
    fi
}


music() {
    LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open music_win 
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_SONG" ]]; then
        ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar \
            prompt_win_off prompt_win_reboot
        rm $HOME/.cache/eww-*.lock
        touch "$LOCK_FILE_SONG"
        run && echo "ok good!"
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close music_win
        rm "$LOCK_FILE_SONG" && echo "closed"
    fi
}


audio() {
    LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open audio_ctl 
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
        ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar music \
            prompt_win_reboot prompt_win_off
        rm $HOME/.cache/eww-*.lock
        touch "$LOCK_FILE_AUDIO"
        run && echo "ok good!"
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close audio_ctl
        rm "$LOCK_FILE_AUDIO" && echo "closed"
    fi
}

prompt_off() {
    LOCK_FILE_PROMPT="$HOME/.cache/eww-prompt_off.lock"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open prompt_win_off
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_PROMPT" ]]; then
        ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar music \
            prompt_win_reboot
        rm $HOME/.cache/eww-*.lock
        touch "$LOCK_FILE_PROMPT"
        run && echo "ok good!"
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close prompt_win_off
        rm "$LOCK_FILE_PROMPT" && echo "closed"
    fi
}

prompt_reboot() {
    LOCK_FILE_PROMPT="$HOME/.cache/eww-prompt_reboot.lock"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open prompt_win_reboot
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_PROMPT" ]]; then
        ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar music \
            prompt_win_off
        rm $HOME/.cache/eww-*.lock
        touch "$LOCK_FILE_PROMPT"
        run && echo "ok good!"
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close prompt_win_reboot
        rm "$LOCK_FILE_PROMPT" && echo "closed"
    fi
}


if [ "$1" = "calendar" ]; then
    calendar
elif [ "$1" = "system" ]; then
    system
elif [ "$1" = "music" ]; then
    music
elif [ "$1" = "audio" ]; then
    audio
elif [ "$1" = "prompt_off" ]; then
    prompt_off
elif [ "$1" = "prompt_reboot" ]; then
    prompt_reboot
fi
