[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "-" ]
run  = "leave"
desc = "Go back to parent directory"

[[manager.prepend_keymap]]
on   = [ "_" ]
run  = "link"
desc = "Symlink the absolute path of yanked files"

[[manager.prepend_keymap]]
on   = [ "<A-u>" ]
run  = "seek -5"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
on   = [ "<A-d>" ]
run  = "seek 5"
desc = "Seek down 5 units in the preview"

[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/ws"
desc = "Go to the projects directory"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on   = "<A-p>"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

