#!/bin/bash

alias vim="nvim"
alias cfvrc="vim ${HOME}/.vim/vimrc"
alias cfnvim="vim ${HOME}/.dotfiles/nvim/.config/nvim"
alias cfbrc="vim ${HOME}/.dotfiles/wsl2/.bashrc"
alias src="source ${HOME}/.bashrc; bind -f ${HOME}/.inputrc"
alias cfal="vim ${HOME}/.dotfiles/wsl2/.bash_aliases"
alias cftm="vim ${HOME}/.dotfiles/tmux/.tmux.conf"
alias sl="sl -e"
alias g="git"
alias c="clear"
alias pcd="__peco_change_dir"
alias pvi="__peco_open_file"
alias cat="bat"
alias ls="lsd"
alias tree="lsd --tree"
alias tmux="history -a; tmux"
