#!/bin/bash

alias l="ls"
alias rm="rm -i"
alias vim="nvim"
alias sl="sl -e"
alias g="git"
alias c="clear"
alias pcd="__peco_change_dir"
alias pvi="__peco_open_file"
alias cat="bat"
alias ls="lsd"
alias lsc="lsd --color never"
alias llc="lsd -al --color never"
alias tree="lsd --tree"
alias tmux="history -a; tmux"
alias py3="python3"
alias ipy3="ipython3"
alias emd="/usr/bin/emacs --daemon |& tee /dev/shm/emacs-daemon.log"
alias emc="/usr/bin/emacsclient -n"
alias less="less -R"
alias mol="molecule"
alias dk="docker"
alias ta="tmux attach"
alias tm="history -a; /usr/local/bin/tmux"
alias nf="neofetch"
alias hxd="hexedit --color"
alias podman-remote="podman --remote"

alias cfvrc="vim ${HOME}/.vim/vimrc"
alias cfnvim="pushd ${HOME}/.dotfiles/nvim/.config/nvim/ && vim init.lua && popd"
alias cfbrc="vim ${HOME}/.dotfiles/wsl2/.bashrc"
alias src="source ${HOME}/.bashrc; bind -f ${HOME}/.inputrc"
alias cfal="vim ${HOME}/.dotfiles/wsl2/.bash_aliases"
alias cftm="vim ${HOME}/.dotfiles/tmux/.tmux.conf"
alias cfwt="vim ${HOME}/host-home/.wezterm.lua"
alias cfzl="vim ${HOME}/.dotfiles/zellij/.config/zellij/config.kdl"
