#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# picom --experimental-backends &

# $HOME/.config/polybar/launch.sh
$HOME/.fehbg &

TERMINAL="alacritty"

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return  spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback
hc keybind Shift-Print  spawn scrot '/home/d0ublew/pictures/screenshots/%Y-%m-%d_$wx$h.png' --select
hc keybind Mod1-Print   spawn scrot '/home/d0ublew/pictures/screenshots/%Y-%m-%d_$wx$h.png'
hc keybind $Mod-F7      spawn $HOME/bin/toggle-theme.sh
hc keybind $Mod-Shift-w spawn $HOME/.config/herbstluftwm/scripts/windowmenu.sh

hc keybind $Mod-w       spawn $HOME/.config/herbstluftwm/scripts/rofi_hlwm.sh \
    -show window

hc keybind $Mod-Shift-o spawn $HOME/.config/herbstluftwm/scripts/rofi_hlwm.sh \
    -show drun

hc keybind $Mod-Escape  spawn $HOME/.config/herbstluftwm/scripts/rofi_hlwm.sh \
    -show power-menu \
    -modi power-menu:$HOME/.config/rofi/power-menu/rofi-power-menu \
    -config $HOME/.config/rofi/power-menu/power-menu.rasi

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-s       split   bottom  0.5
hc keybind $Mod-v       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} 10 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
# hc keybind $Mod-period use_index +1 --skip-visible
# hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-f floating toggle
hc keybind $Mod-z fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc keybind $Mod-F9 cycle_value frame_gap 0 8 16 24 32
hc keybind $Mod-Shift-F9 cycle_value frame_gap 32 24 16 8 0
hc keybind $Mod-F10 cycle_value window_gap 0 8 16 24 32
hc keybind $Mod-Shift-F10 cycle_value window_gap 32 24 16 8 0
# hc keybind $Mod-F11 set smart_window_surroundings on
# hc keybind $Mod-Shift-F11 set smart_window_surroundings off
hc keybind $Mod-F11 set frame_border_width 0
hc keybind $Mod-Shift-F11 set frame_border_width 2
hc keybind $Mod-F12 set_attr theme.title_height 16
hc keybind $Mod-Shift-F12 set_attr theme.title_height 0

# hc keybind XF86AudioRaiseVolume spawn pamixer -i 1
# hc keybind XF86AudioLowerVolume spawn pamixer -d 1
# hc keybind XF86AudioMute spawn pamixer -t

hc keybind $Mod-F3 spawn /home/d0ublew/bin/volume.sh up
hc keybind $Mod-F2 spawn /home/d0ublew/bin/volume.sh down
hc keybind $Mod-F1 spawn /home/d0ublew/bin/volume.sh mute

hc keybind $Mod-Shift-F1 spawn playerctl play-pause -p spotify

hc keybind $Mod-b spawn /home/d0ublew/.local/bin/eww open bar
hc keybind $Mod-Shift-b spawn /home/d0ublew/.local/bin/eww close bar

# theme
[ -f $HOME/.config/herbstluftwm/themes/colors/default.sh ] && \
    source $HOME/.config/herbstluftwm/themes/colors/default.sh

# [ -f $HOME/.config/herbstluftwm/themes/styles/default.sh ] && \
#     source $HOME/.config/herbstluftwm/themes/styles/default.sh

[ -f $HOME/.config/herbstluftwm/themes/styles/inner_border.sh ] && \
    source $HOME/.config/herbstluftwm/themes/styles/inner_border.sh

# source $HOME/.config/herbstluftwm/themes/colors/tokyonight_day.sh
# source $HOME/.config/herbstluftwm/themes/styles/single_border.sh

hc set frame_gap 0
hc set window_gap 8
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
# hc set smart_frame_surroundings hide_gaps
hc set mouse_recenter_gap 0
hc set hide_covered_windows true

hc set_layout grid

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=center floating_geometry=800x600
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc rule class='waterfox' --tag=10 --focus=on
hc rule class='Spotify' --tag=9 --focus=on
hc rule class='discord' --tag=8 --focus=on
hc rule class='Pcmanfm' --tag=5 --focus=on
hc rule class='sioyek' --tag=3 --focus=on

hc rule title~'nmtui.sh' floating=on floatplacement=center floating_geometry=800x600

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

hc pad 0 32 8 8 8

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# hc set_monitors 1920x1036+0+44

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
